CONTRIBUTING.md
README.md

-Created a CONTRIBUTING.md (Issue #5)
-Added a README.md (Issue #6)
-Made and Added a logo in README.md #6 
Fixes # (issue)
- Are there environment variables that should be set? …

docs: #5 Created a CONTRIBUTING.md and #6 Added a README.md

---

components/Dashboard/DashboardSidebar/index.tsx
components/Dashboard/FormPreview.tsx
components/Dashboard/ReviewForm.tsx

Fixes #15
- Are there environment variables that should be set?
- I haven't checked if new and existing unit tests pass locally with my changes

fix: Dark mode and text area bug

---

pages/__app/signup.tsx

I added the `lastName` field to the default values in the `form` object.
Fixes #13
https://www.loom.com/share/a240e581a69243e2b4d8abab4039166e?sid=df86630f-53d6-46c4-a5dc-ff14df25cd45
- no error even after input changes
1. Visit the signup page by navigating to http://app.localhost:3000/signup.
2. On the signup page, locate the "Last Name" input field.
3. Make any changes or edits in the "Last Name" input field.

fix: Fixes uncontrolled input at signup page

---

CONTRIBUTING.md

docs: Add Reference to Backend Repository

---

README.md

Updates the Licensing in the README.md file
Fixes #35

docs: updated the README licence

---

pages/__app/dashboard/index.tsx

I resolved the issue by changing the `w-screen` to `w-full`.
Fixes #30
Visit the signup page by navigating to http://app.localhost:3000/dashboard.

fix: Fixes overflow at dashboard page

---

public/logo.svg

fix: resolved logo svg bug #39

---

components/Dashboard/DashboardSidebar/index.tsx

Resolved overflow issue on dashboard page by adding `max-w-[107px]` constraint to the `<p>` tag for user's name display.
Fixes #43 and #41
- If my code is correct, please consider both issues resolved and close them accordingly.
- Removed the horizontal scrollbar.
- Added ellipsis (...) for name display if it exceeds available space.
1.Visit the signup page by navigating to http://app.localhost:3000/dashboard.

fix: Resolves scroll problem in sidebar on the dashboard page

---

pages/__app/signup.tsx

@hemantwasthere Hey bro, it looks like these commits were accidentally left out in pull request #17. As we previously discussed the implementation of the lastname functionality, could you please go ahead and merge them? Thanks!
```
lastName: z.string().refine(
(value) => value === "" || (value.length >= 3 && value.length <= 25),
{
message: 'Last name must be between 3 and 25 characters'
}
).optional(),
```
I've tested it locally, and it's functioning correctly. Please review it; otherwise, I will removing the 'min' and 'max'.

fix: Include Left Out Lastname Functionality Code in PR #17

---

layouts/DashboardLayout.tsx

fix the disappearing sidebar and dashboard logo when the reactQuerydev tools is shifted to top 
Fixes #71 
fix in tailwind css

fix: fixed issue number 71! 

---

pages/__app/dashboard/index.tsx

Revert "feat: Add authentication requirement for accessing the dashboard"

---

components/Dashboard/FormPane.tsx

Fixes # (issue)
#120 #106
- Are there environment variables that should be set?
- I haven't checked if new and existing unit tests pass locally with my changes

fix: multi select form check

---

README.md

Fixes #125 
- Are there environment variables that should be set?
- I haven't checked if new and existing unit tests pass locally with my changes

feat: A new feature (Contributers added in readme)

---

CONTRIBUTING.md
README.md

Adds quick video guide to setup project locally.
Fixes #177 
loom video for setup : https://www.loom.com/share/c0a60e1e37ad4451bfa7435027661ea4?sid=dd73cc47-7f77-4711-b4d1-fce01efe42c7
- Are there environment variables that should be set - yes

feat: added video to setup locally

---

components/Dashboard/DashboardSidebar/index.tsx

This PR fixes this bug related to the sidebar tab styling issue in the DashboardSidebar component and ensures that the active tab is styled correctly.
Fixes #170 
Loom Video:  [https://www.loom.com/share/c7868a6219604ccc8269d6807d6d3475?sid=7666a48a-046a-4467-b91a-a9fe6c6fa382](https://www.loom.com/share/c7868a6219604ccc8269d6807d6d3475?sid=7666a48a-046a-4467-b91a-a9fe6c6fa382)
To test this PR:
- Navigate to the dashboard.
- Observe the styling of the tabs in the sidebar.
- Click on different tabs and ensure that the active tab is correctly styled.
- Verify that the styling updates as expected when switching between tabs.

fix: sidebar tab active style changes

---

next.config.js
pages/templates/ebraj/about.tsx
pages/templates/ebraj/index.tsx

This PR included the Minimal About Us page with minor modification of the index page for review app.
Ref #169 
Video Link Showcasing the UI - https://www.loom.com/share/c98de7e388bb46d68caedc3386682458?sid=f90c478c-85ce-4e0c-a76e-c8675ae451c4

feat: about-us page added | index minor updates

---

components/Dashboard/FormPane.tsx

Overview: This PR adds a feature to the button component that and opens the dynamic URL in a new browser tab when clicked.
This functionality enhances the user experience by providing an easy way to open a dynamically generated URL in a new tab, improving usability.
Fixes #204
[Untitled_ Oct 20, 2023 1_34 AM.webm](https://github.com/piyushgarg-dev/review-app/assets/134006296/f4a41679-bdd6-4e28-8552-832c201d0cde)
No documentation required.
- Click on the url and it will now open in a new tab

feat: open form link on click #204

---

pages/templates/ebraj/index.tsx

Fixes #190 while clicking on logo or name it does not redirects to the home page like any other website
Solution on clicking name and logo redirect to the home page.
Solution by using useRouter
Style is updated to cursor pointer
https://github.com/piyushgarg-dev/review-app/assets/63500076/8ceb35c5-4d60-4695-9b3b-11ae9479364c

fix: Clickable Icon #190

---

components/Modals/ProjectModal.tsx

Adds validation when the user tries to create a project with a duplicate subdomain.
Fixes #115 
https://www.loom.com/share/23858ee2a05e44ad9962de3dc060fe2d?sid=7094f1ae-0438-4d7c-adcf-dd34cc313f7e
Just try to create a project with an already existing subdomain, after logging in.

fix: Added FE validation for duplicate subdomain

---

pages/[...slug].tsx

**Description**:
I have created this pull request to add an error page for improved user experience in case of 404 errors. The changes in this pull request include:
- Added the "Custom404.tsx" file in the "pages" folder.
- Improved the UI of the error page with a friendly message and a link to the homepage/dashboard.
- Updated the main layout to include the error page in the navigation.
**Related Issue**:
- This pull request addresses issue #122 .
feat: Add [...slug].tsx for error page
**Checklist**:
**Additional Comments**:
I'm open to feedback and suggestions for further improvements. The error page is designed to enhance the user experience in the event of 404 errors. The code follows the project's style and conventions.
https://github.com/piyushgarg-dev/review-app/assets/138546450/930c …

Add [...slug].tsx for error page

---

pages/templates/ebraj/index.tsx
styles/globals.css

Fixes #211 
Loom Video: https://www.loom.com/share/6968b11099364a0688e49c0a4d7654b8
https://www.radix-ui.com/primitives/docs/components/dropdown-menu
- Are there environment variables that should be set? Just the one which is given in the documentation to run the app locally
- What are the minimal test data to have? Nothing, just the home page
- What is expected (happy path) to have (input and output)? Navbar should not distort while changing the theme 
- Any other important info that could help to test that PR? No

fix: Layout shift on Landing page

---

pages/__app/dashboard/[domain]/index.tsx

Fixed Issue #215 
Fixes #215 
BEFORE:
AFTER:
feature
login to review-app and you can see the changes
- I haven't checked if new and existing unit tests pass locally with my changes

feat: Improved project details UI

---

pages/__app/signup.tsx

This will put the correct placeholder to password field in signup form.
Fixes #219

fix: fix the password placeholder

---

pages/templates/ebraj/index.tsx

This PR adds an Input Text to the "Join Our Community" input section for better UX
Fixes # (issue)
Before:
After:
- Go to the Landing Page
- Scroll to the About Section
- Go to the "Join Our Community" and check the input section

feat: added placeholder text and adjusted ui of input

---

components/Dashboard/ProjectSwitch.tsx

This PR changes the styling of the Create Project button, to make it similar to the other buttons present in the app
Fixes #231
https://www.loom.com/share/6540996e7e334ab892c06aeff079c448
1. Login / Signup into the application
2. Go to dashboard
3. Click of the Projects Dropdown at the top right side of the navbar
4. Check the new styles for the Create Project button

feat: changed styling of Create Project Button

---

components/Dashboard/FormEdit.tsx

This PR enhances the background color of the logo in the dark mode of the Form Edit section
Fixes #258 
Screenshot of changes:

Enhanced Form Edit Logo background in dark mode

---

components/Dashboard/ReviewForm.tsx

This PR adds dark mode colors to the ReviewForm
Fixes #233 
Before : 
After:
- Create a new form via Dashboard
- Go to the Review Form and check the UI

feat: dark mode added to the review form

---

components/Dashboard/DashboardMobileSidebar/index.tsx

This PR correct the code to show the menu icon button in navbar in mobile view.
Currently, the menu icon disappear in testimonial section of dashboard in mobile view.
Fixes #265
Before:
After:
Go to Dashboard in mobile view, click on testimonial section, the menu icon in navbar disappeared and there is no way to access the sidebar now.

fix: Added menu icon on testimonial page of Dashboard in mobile view

---

components/Dashboard/DashboardNavbar/index.tsx

This PR adds an Icon to the Dashboard Navbar Logout Button and adjusts the mobile view to display only icon in short viewports
Fixes #261 
Before :
After:
- Login to the Dashboard and Check the Navbar
- Check the Mobile View as well

feat: logout icon added to navbar button and mobile view adjusted

---

pages/templates/ebraj/index.tsx

Fixes # 
Landing page main image dark mode seems have darken too much of the image reduced the dark part there. (Makes it hard to see the image at all)
Typos in the main text of landing page and footer text.
Removed some extra spaces in tailwind classnames.
- Are there environment variables that should be set? - No
- What are the minimal test data to have? - N/A
- What is expected (happy path) to have (input and output)? - N/A
- Any other important info that could help to test that PR - N/A
This is my first PR here can really use some feedback from you guys.

refactor: Fixed typos in landing page and some tailwind class extra spaces
